version: '3'
services:
  bookwiseapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: ["/usr/src/app/bookwiseAPI"]